---
- name: Select supported vos params
  set_fact:
    _supported_vos_data_list: "{{ brut_vo_data | selectattr('name', 'in', gridsite_supported_vos) }}"

# Combine with vo details
- name: Combine with vo details
  set_fact:
    _supported_vos_data_list: "{{ _supported_vos_data_list | community.general.lists_mergeby(vo_details, 'name') }}"

# Combining with our local data
- name: Combine with local parameters
  set_fact:
    _supported_vos_data_list: "{{ _supported_vos_data_list | community.general.lists_mergeby(gridsite_supported_vo_params, 'name') }}"

# Ensure all VO have a role, even empty:
- name: Normalize list to ensure every dict has a roles entry, even empty (easier for subsequent processing)
  set_fact:
    gridsite_supported_vos_data_list: "{{ _supported_vos_data_list | map('combine', {'roles': [] | default([])}) | list }}"
