---
# Called from tasks/grid_users_n_groups.yml
# Add main vo group
- name: Main VO group
  set_fact:
    _vo_data_new: "{{ _vo_data | combine( { 'group': _vo_data.name, 'gid': _vo_data.base_uid } ) }}"

# Reset pool accounts list
- name: Reset pool accounts list
  set_fact:
    _vo_pool_accounts: []

# Generate main VO user pool accounts list
- name: Main VO user pool accounts
  set_fact:
    _vo_pool_accounts: "{{ _vo_pool_accounts + [ { 
      'account': _vo_data.account_prefix + '%03d' | format(ansible_loop.index),
      'comment': 'VO ' + _vo_data.name + ' pool account',
      'uid': _vo_data.base_uid + 1000 + ansible_loop.index } ] }}"
  loop: '{{ range(1 , gridsite_vo_pool_accounts_count+1)  | list }}'
  loop_control:
    extended: true

# Combine main VO user pool accounts list with _vo_data
- name: Combine main VO user pool accounts with _vo_data
  set_fact:
    _vo_data_new: "{{ _vo_data_new | combine({ 'pool_accounts': _vo_pool_accounts }) }}"

# Temporary roles list
- name: Temporary roles list
  set_fact:
    _roles_data_list_new: []

# Iterate over roles to create subgroups and users
- name: Create subgroups and users
  include_tasks: 'tasks/grid_vo_roles.yml'
  loop: "{{ _vo_data_new.roles }}"
  loop_control:
    loop_var: '_roles_data'

# Modify voms_mapping item with _voms_mapping_list_new
- name: Merge roles_data item with _roles_list_new in _vo_data_new
  set_fact:
    _vo_data_new: "{{ _vo_data_new | combine({ 'roles': _roles_data_list_new }) }}"

# Put it int a new gridsite_supported_vos_data_list
- name: Add it to the temporary gridsite_supported_vos_data_list
  set_fact:
    _gridsite_supported_vos_data_list_new: "{{ _gridsite_supported_vos_data_list_new + [ _vo_data_new ] }}"
