---
# tasks file for ansible-role-gridsite

# If needed, get all the VO data from EGI API
- name: Call get VO data task
  include_tasks:
    file: 'tasks/get_vo_data.yml'
  when: "'htc_nodes' in group_names"

# If slurm node, include slurm vars
- name: Include slurm configuration
  include_vars:
    file: 'vars/slurm.yml'
  when: "'slurm_nodes' in group_names"

# If slurm node, run task to generate needed vars
- name: Generate slurm vars
  include_tasks:
    file: 'tasks/slurm.yml'
  when: "'slurm_nodes' in group_names"

# If list of grid user is needed, generates it
- name: Generate list of grid users
  include_tasks:
    file: 'tasks/grid_users_n_groups.yml'
  when: "'ce_arc' in group_names or 'grid_wn' in group_names"

# If group is grid_wn, include wn tasks
- name: Include grid_wn tasks
  include_tasks:
    file: 'tasks/grid_wn.yml'
  when: "'grid_wn' in group_names"

# If group is ce_arc, include ce_arc vars
- name: Include ce_arc configuration
  include_vars:
    file: 'vars/ce_arc.yml'
  when: "'ce_arc' in group_names"
