---
# tasks file to generate slurm vars

# Create list of slurm compute nodes (grid WNs)
- name: Set empty slurm_compute_nodes
  set_fact:
    slurm_nodelist: []

 # FIXME: CoreSpecCount / MemSpecLimit / Reservations : those are more usefull, as the following values are know to slurm.
- name: Slurm nodes list
  set_fact:
    slurm_nodelist: "{{ slurm_nodelist + [ { 'NodeName': item, 'CPUs': hostvars[item]['ansible_facts']['processor_vcpus'], 'RealMemory': hostvars[item]['ansible_facts']['memtotal_mb'] } ] }}"
  loop: "{{ gridsite_list_of_wns }}"

# Reset slurm_partitionlist: seems it *must* have a default partition
# FIXME: "ALL" is all what it can do for partitions, for now.
- name: Reset slurm_partitionlist
  set_fact:
    slurm_partitionlist: "{{ [ {
    'PartitionName': 'normal',
    'Nodes': 'ALL',
    'Default': 'YES',
    'MaxTime': slurm_max_job_time,
    'State': 'UP',
    'DefaultTime': slurm_job_def_time} ] }}"

# Generation of slurm partitions from supported_vos
# FIXME: "ALL" is all what it can do for partitions, for now.
- name: Generate slurm partitions list
  set_fact:
    slurm_partitionlist: "{{ slurm_partitionlist + [ {
    'PartitionName': item,
    'Nodes': 'ALL',
    'Default': 'NO',
    'MaxTime': slurm_max_job_time,
    'State': 'UP',
    'DefaultTime': slurm_job_def_time } ] }}"
  loop: "{{ gridsite_supported_vos }}"

# Add local slurm partitions (FIXME: hardcoded for now)
- name: Add local slurm partitions
  set_fact:
    slurm_partitionlist: "{{ slurm_partitionlist + [ {
    'PartitionName': 'sbg_local',
    'Nodes': 'ALL',
    'Default': 'NO',
    'MaxTime': slurm_max_job_time,
    'State': 'UP',
    'DefaultTime': slurm_job_def_time } ] }}"